In [1]:
import pandas as pd
import numpy as np

In [2]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [3]:
model = Sequential()

model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

model.summary()

c:\Users\IRVINEi\miniconda3\envs\polynominal_regression\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[-0.00971681,  0.5162372 ,  0.02284253],
       [ 0.4521113 , -0.24050659, -0.50804853],
       [-0.26598352,  0.09343475, -0.40631735],
       [-0.39984038,  0.70515007,  0.28333515],
       [ 0.09367776,  0.12609029, -0.04381019]], dtype=float32)

In [5]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[ 0.5725846 ,  0.8185569 , -0.04595116],
       [ 0.02207193, -0.07141922, -0.99720216],
       [ 0.8195484 , -0.5699684 ,  0.05896065]], dtype=float32)

In [6]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)